/// Everything here is generated by ChatGPT, someone has to verify the correctness of the data
export class PhysicalConstants {

    // Planck constant (J * s)
    public static readonly PLANCK_CONSTANT: number = 6.62607015e-34; // CODATA 2018

    // Reduced Planck constant (J * s)
    public static readonly REDUCED_PLANCK_CONSTANT: number = 1.054571817e-34; // CODATA 2018

    // Speed of light in a vacuum (m/s)
    public static readonly SPEED_OF_LIGHT: number = 299792458; // CODATA 2018

    // Gravitational constant (N * m^2 / kg^2)
    public static readonly GRAVITATIONAL_CONSTANT: number = 6.67430e-11; // CODATA 2018
    public static readonly G: number = 9.81; // CODATA 2014

    // Coulomb constant (N * m^2 / C^2)
    public static readonly COULOMB_CONSTANT: number = 8.9875517923e9; // CODATA 2018

    // Avogadro constant (1/mol)
    public static readonly AVOGADRO_CONSTANT: number = 6.02214076e23; // CODATA 2018

    // Boltzmann constant (J/K)
    public static readonly BOLTZMANN_CONSTANT: number = 1.380649e-23; // CODATA 2018

    // Gas constant (J/mol * K)
    public static readonly GAS_CONSTANT: number = 8.314462618; // CODATA 2018

    // Faraday constant (C/mol)
    public static readonly FARADAY_CONSTANT: number = 96485.33212; // CODATA 2018

    // Stefan-Boltzmann constant (W/m^2 * K^4)
    public static readonly STEFAN_BOLTZMANN_CONSTANT: number = 5.670374419e-8; // CODATA 2018

    // Wien displacement law constant (m * K)
    public static readonly WIEN_DISPLACEMENT_CONSTANT: number = 2.897771955e-3; // CODATA 2018

    // Universal gas constant (J/mol * K)
    public static readonly UNIVERSAL_GAS_CONSTANT: number = 8.3144598; // IUPAC 1997

    // Rydberg constant (1/m)
    public static readonly RYDBERG_CONSTANT: number = 10973731.568160; // CODATA 2018

    // Vacuum permittivity (F/m)
    public static readonly VACUUM_PERMITTIVITY: number = 8.8541878128e-12; // CODATA 2018

    // Vacuum permeability (N/A^2)
    public static readonly VACUUM_PERMEABILITY: number = 1.25663706212e-6; // CODATA 2018

    // Elementary charge (C)
    public static readonly ELEMENTARY_CHARGE: number = 1.602176634e-19; // CODATA 2018

    // Magnetic constant (N/A^2)
    public static readonly MAGNETIC_CONSTANT: number = 1.25663706212e-6; // CODATA 2018

    // Electric constant (F/m)
    public static readonly ELECTRIC_CONSTANT: number = 1 / (PhysicalConstants.VACUUM_PERMEABILITY * PhysicalConstants.SPEED_OF_LIGHT * PhysicalConstants.SPEED_OF_LIGHT);

    // Bohr magneton (J/T)
    public static readonly BOHR_MAGNETON: number = 9.2740100783e-24; // CODATA 2018

    // Nuclear magneton (J/T)
    public static readonly NUCLEAR_MAGNETON: number = 5.0507837461e-27; // CODATA 2018

    // Conductance quantum (S)
    public static readonly CONDUCTANCE_QUANTUM: number = 7.748091729e-5; // CODATA 2018

    // Josephson constant (Hz/V)
    public static readonly JOSEPHSON_CONSTANT: number = 483597.8484e9; // CODATA 2018

    // Von Klitzing constant (Ohm)
    public static readonly VON_KLITZING_CONSTANT: number = 25812.80745; // CODATA 2018
    // Atomic mass unit (kg)
    public static readonly ATOMIC_MASS_UNIT: number = 1.66053906660e-27; // CODATA 2018

    // Electron mass (kg)
    public static readonly ELECTRON_MASS: number = 9.1093837015e-31; // CODATA 2018

    // Proton mass (kg)
    public static readonly PROTON_MASS: number = 1.67262192369e-27; // CODATA 2018

    // Neutron mass (kg)
    public static readonly NEUTRON_MASS: number = 1.67492749804e-27; // CODATA 2018

    // Fine-structure constant
    public static readonly FINE_STRUCTURE_CONSTANT: number = 7.2973525693e-3; // CODATA 2018

    // Bohr radius (m)
    public static readonly BOHR_RADIUS: number = PhysicalConstants.FINE_STRUCTURE_CONSTANT * Math.pow(PhysicalConstants.REDUCED_PLANCK_CONSTANT, 2) / (4 * Math.PI * PhysicalConstants.ELEMENTARY_CHARGE * PhysicalConstants.SPEED_OF_LIGHT); // NIST 2019

    // Electron volt (J)
    public static readonly ELECTRON_VOLT: number = 1.602176634e-19; // CODATA 2018

    // Fermi coupling constant (GeV^-2)
    public static readonly FERMI_COUPLING_CONSTANT: number = 1.1663787e-5; // PDG 2020

    // Neutrino mixing angle sin^2(theta_12)
    public static readonly NEUTRINO_MIXING_ANGLE_SIN_SQUARED_12: number = 0.297; // PDG 2020

    // Neutrino mixing angle sin^2(theta_13)
    public static readonly NEUTRINO_MIXING_ANGLE_SIN_SQUARED_13: number = 0.0215; // PDG 2020

    // Neutrino mixing angle sin^2(theta_23)
    public static readonly NEUTRINO_MIXING_ANGLE_SIN_SQUARED_23: number = 0.57; // PDG 2020

    // CP-violating phase in the PMNS matrix (degrees)
    public static readonly CP_VIOLATING_PHASE_PMNS_DEGREES: number = 0; // PDG 2020

    // Weak mixing angle (degrees)
    public static readonly WEAK_MIXING_ANGLE_DEGREES: number = 29.59; // PDG 2020

    // Weinberg angle (degrees)
    public static readonly WEINBERG_ANGLE_DEGREES: number = 28.746; // PDG 2020

    // Dirac constant (J s)
    public static readonly DIRAC_CONSTANT: number = PhysicalConstants.REDUCED_PLANCK_CONSTANT / 2;


    // Electric permittivity of vacuum (F/m)
    public static readonly ELECTRIC_PERMITTIVITY_VACUUM: number = 8.8541878128e-12; // CODATA 2018

    // Electron Compton wavelength (m)
    public static readonly ELECTRON_COMPTON_WAVELENGTH: number = PhysicalConstants.REDUCED_PLANCK_CONSTANT / (PhysicalConstants.ELECTRON_MASS * PhysicalConstants.SPEED_OF_LIGHT);

    // Proton Compton wavelength (m)
    public static readonly PROTON_COMPTON_WAVELENGTH: number = PhysicalConstants.REDUCED_PLANCK_CONSTANT / (PhysicalConstants.PROTON_MASS * PhysicalConstants.SPEED_OF_LIGHT);
    // Hubble constant (km/s/Mpc)
    public static readonly HUBBLE_CONSTANT: number = 73.3; // Planck 2018

    // Critical density of the universe (kg/m^3)
    public static readonly CRITICAL_DENSITY_UNIVERSE: number = 1.8788e-26 * PhysicalConstants.HUBBLE_CONSTANT ** 2; // Planck 2018

    // Baryon density of the universe (kg/m^3)
    public static readonly BARYON_DENSITY_UNIVERSE: number = 0.048 * PhysicalConstants.CRITICAL_DENSITY_UNIVERSE; // Planck 2018

    // Dark matter density of the universe (kg/m^3)
    public static readonly DARK_MATTER_DENSITY_UNIVERSE: number = 0.259 * PhysicalConstants.CRITICAL_DENSITY_UNIVERSE; // Planck 2018

    // Dark energy density of the universe (kg/m^3)
    public static readonly DARK_ENERGY_DENSITY_UNIVERSE: number = 0.693 * PhysicalConstants.CRITICAL_DENSITY_UNIVERSE; // Planck 2018

    // Age of the universe (s)
    public static readonly AGE_UNIVERSE: number = 4.354e17; // Planck 2018

    // Size of the observable universe (m)
    public static readonly SIZE_OBSERVABLE_UNIVERSE: number = 8.798e26; // Planck 2018

    // Cosmic microwave background temperature (K)
    public static readonly CMB_TEMPERATURE: number = 2.7255; // Planck 2018

    // Recombination temperature (K)
    public static readonly RECOMBINATION_TEMPERATURE: number = 3000; // Estimate

    // Density perturbations amplitude
    public static readonly DENSITY_PERTURBATIONS_AMPLITUDE: number = 5e-5; // Planck 2018

    // Scalar spectral index
    public static readonly SCALAR_SPECTRAL_INDEX: number = 0.965; // Planck 2018

    // Tensor-to-scalar ratio
    public static readonly TENSOR_TO_SCALAR_RATIO: number = 0.01; // Estimate

    // Neutrino density (kg/m^3)
    public static readonly NEUTRINO_DENSITY: number = 112 * (PhysicalConstants.CMB_TEMPERATURE / 2.7255) ** 4 / (PhysicalConstants.HUBBLE_CONSTANT / 100) ** 3; // Estimate based on Planck 2018

    // Neutrino decoupling temperature (K)
    public static readonly NEUTRINO_DECOUPLING_TEMPERATURE: number = 1.1e10; // Estimate based on Big Bang nucleosynthesis

    // Photon decoupling temperature (K)
    public static readonly PHOTON_DECOUPLING_TEMPERATURE: number = 3e5; // Estimate based on Big Bang nucleosynthesis
}